// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Block                = require("bs-platform/lib/js/block.js");
var Curry                = require("bs-platform/lib/js/curry.js");
var WebSockets           = require("bs-websockets/lib/js/src/webSockets.js");
var TitleCase            = require("title-case");
var Js_primitive         = require("bs-platform/lib/js/js_primitive.js");
var TelepathicActions    = require("./TelepathicActions.js");
var ProjectNameGenerator = require("project-name-generator");

var Config = /* module */[/* keys : record */[/* userName */"telepathic:userName"]];

function chooseName() {
  return TitleCase(ProjectNameGenerator({
                  alliterative: /* true */1
                }).spaced);
}

function getName() {
  return Js_primitive.null_to_opt(localStorage.getItem("telepathic:userName"));
}

function updateName(name) {
  localStorage.setItem("telepathic:userName", name);
  return /* () */0;
}

function makeName() {
  var name = chooseName(/* () */0);
  updateName(name);
  return name;
}

function getOrCreateUserName() {
  var name = getName(/* () */0);
  if (name) {
    return name[0];
  } else {
    return makeName(/* () */0);
  }
}

function sendMessage(linkId, text, client) {
  var userName = getOrCreateUserName(/* () */0);
  var message = /* MessageSend */Block.__(0, [
      linkId,
      userName,
      text
    ]);
  client[/* ws */0].send(JSON.stringify(TelepathicActions.encode(message)));
  return /* () */0;
}

function register(client) {
  var message = /* ClientRegister */Block.__(2, [client[/* linkId */1]]);
  client[/* ws */0].send(JSON.stringify(TelepathicActions.encode(message)));
  return /* () */0;
}

function make($staropt$star, linkId, url) {
  var socket = $staropt$star ? $staropt$star[0] : /* None */0;
  return /* record */[
          /* ws */socket ? socket[0] : Curry._1(WebSockets.WebSocket[/* make */0], url),
          /* linkId */linkId
        ];
}

exports.Config              = Config;
exports.chooseName          = chooseName;
exports.getName             = getName;
exports.updateName          = updateName;
exports.makeName            = makeName;
exports.getOrCreateUserName = getOrCreateUserName;
exports.sendMessage         = sendMessage;
exports.register            = register;
exports.make                = make;
/* title-case Not a pure module */
