// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var Curry             = require("bs-platform/lib/js/curry.js");
var Telepathic        = require("./Telepathic.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function make(options) {
  var client = Curry._3(Telepathic.Client[/* make */8], /* None */0, options.linkId, options.url);
  return {
          makeName: (function () {
              return Curry._1(Telepathic.Client[/* makeName */4], /* () */0);
            }),
          getName: (function () {
              return Js_null_undefined.from_opt(Curry._1(Telepathic.Client[/* getName */2], /* () */0));
            }),
          updateName: (function (name) {
              return Curry._1(Telepathic.Client[/* updateName */3], name);
            }),
          getOrCreateUserName: (function () {
              return Curry._1(Telepathic.Client[/* getOrCreateUserName */5], /* () */0);
            }),
          sendMessage: (function (text) {
              return Curry._3(Telepathic.Client[/* sendMessage */6], client[/* linkId */1], text, client);
            })
        };
}

var start = make;

exports.make  = make;
exports.start = start;
/* Telepathic Not a pure module */
