// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict';

var TelepathicUtils   = require("./TelepathicUtils.js");
var TelepathicClient  = require("./TelepathicClient.js");
var TelepathicActions = require("./TelepathicActions.js");

var Actions = /* module */[
  /* key */TelepathicActions.key,
  /* decode */TelepathicActions.decode,
  /* encode */TelepathicActions.encode
];

var Client = /* module */[
  /* Config */TelepathicClient.Config,
  /* chooseName */TelepathicClient.chooseName,
  /* getName */TelepathicClient.getName,
  /* updateName */TelepathicClient.updateName,
  /* makeName */TelepathicClient.makeName,
  /* getOrCreateUserName */TelepathicClient.getOrCreateUserName,
  /* sendMessage */TelepathicClient.sendMessage,
  /* register */TelepathicClient.register,
  /* make */TelepathicClient.make
];

var Utils = /* module */[
  /* expectMatches */TelepathicUtils.expectMatches,
  /* objToJson */TelepathicUtils.objToJson,
  /* rejectWith */TelepathicUtils.rejectWith,
  /* cancelTimeout */TelepathicUtils.cancelTimeout
];

exports.Actions = Actions;
exports.Client  = Client;
exports.Utils   = Utils;
/* TelepathicClient Not a pure module */
