// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict'

var Js_exn = require('bs-platform/lib/js/js_exn.js')
var Js_option = require('bs-platform/lib/js/js_option.js')
var Js_primitive = require('bs-platform/lib/js/js_primitive.js')
var Js_null_undefined = require('bs-platform/lib/js/js_null_undefined.js')
var Client$BsTelepathic = require('./Client.bs.js')

function make (options) {
  var callback
  try {
    callback = Js_option.getExn(
      Js_primitive.null_undefined_to_opt(options.onMessage)
    )
  } catch (_exn) {
    callback = Js_exn.raiseError("An 'onMessage' callback is required.")
  }
  var client = Client$BsTelepathic.make(
    /* None */ 0,
    options.linkId,
    callback,
    options.url
  )
  return {
    makeName: function () {
      return Client$BsTelepathic.makeName(/* () */ 0)
    },
    getName: function () {
      return Js_null_undefined.from_opt(Client$BsTelepathic.getName(/* () */ 0))
    },
    updateName: Client$BsTelepathic.updateName,
    getOrCreateUserName: function () {
      return Client$BsTelepathic.getOrCreateUserName(/* () */ 0)
    },
    sendMessage: function (text) {
      return Client$BsTelepathic.sendMessage(
        client[/* linkId */ 1],
        text,
        client
      )
    },
  }
}

var start = make

exports.make = make
exports.start = start
/* Client-BsTelepathic Not a pure module */
