// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict'

import * as Js_exn from 'bs-platform/lib/es6/js_exn.js'
import * as Js_option from 'bs-platform/lib/es6/js_option.js'
import * as Js_primitive from 'bs-platform/lib/es6/js_primitive.js'
import * as Js_null_undefined from 'bs-platform/lib/es6/js_null_undefined.js'
import * as Client$BsTelepathic from './Client.bs.js'

function make (options) {
  var callback
  try {
    callback = Js_option.getExn(
      Js_primitive.null_undefined_to_opt(options.onMessage)
    )
  } catch (_exn) {
    callback = Js_exn.raiseError("An 'onMessage' callback is required.")
  }
  var client = Client$BsTelepathic.make(
    /* None */ 0,
    options.linkId,
    callback,
    options.url
  )
  return {
    makeName: function () {
      return Client$BsTelepathic.makeName(/* () */ 0)
    },
    getName: function () {
      return Js_null_undefined.from_opt(Client$BsTelepathic.getName(/* () */ 0))
    },
    updateName: Client$BsTelepathic.updateName,
    getOrCreateUserName: function () {
      return Client$BsTelepathic.getOrCreateUserName(/* () */ 0)
    },
    sendMessage: function (text) {
      return Client$BsTelepathic.sendMessage(
        client[/* linkId */ 1],
        text,
        client
      )
    },
  }
}

var start = make

export {make, start}
/* Client-BsTelepathic Not a pure module */
