// Generated by BUCKLESCRIPT VERSION 2.2.2, PLEASE EDIT WITH CARE
'use strict';

var Js_exn = require("bs-platform/lib/js/js_exn.js");
var Js_option = require("bs-platform/lib/js/js_option.js");
var Js_primitive = require("bs-platform/lib/js/js_primitive.js");
var Client$Telepathic = require("./Client.bs.js");
var Js_null_undefined = require("bs-platform/lib/js/js_null_undefined.js");

function make(options) {
  var callback;
  try {
    callback = Js_option.getExn(Js_primitive.null_undefined_to_opt(options.onMessage));
  }
  catch (_exn){
    callback = Js_exn.raiseError("An 'onMessage' callback is required.");
  }
  var client = Client$Telepathic.make(Js_primitive.null_undefined_to_opt(options.url), options.linkId, callback, /* () */0);
  return {
          makeName: (function () {
              return Client$Telepathic.makeName(/* () */0);
            }),
          getName: (function () {
              return Js_null_undefined.fromOption(Client$Telepathic.getName(/* () */0));
            }),
          updateName: Client$Telepathic.updateName,
          getOrCreateUserName: (function () {
              return Client$Telepathic.getOrCreateUserName(/* () */0);
            }),
          sendMessage: (function (text) {
              return Client$Telepathic.sendMessage(client[/* linkId */1], text, client);
            })
        };
}

var $$default = {
  start: make
};

exports.make = make;
exports.$$default = $$default;
exports.default = $$default;
exports.__esModule = true;
/* Client-Telepathic Not a pure module */
