// Generated by BUCKLESCRIPT VERSION 2.1.0, PLEASE EDIT WITH CARE
'use strict'

import * as Js_exn from 'bs-platform/lib/es6/js_exn.js'

function expectMatches (message, expected, actual) {
  if (actual !== expected) {
    return Js_exn.raiseError(
      'Failed: ' +
        (message + ('\nExpected: ' + (expected + ('\nActual: ' + actual))))
    )
  } else {
    return 0
  }
}

function objToJson (obj) {
  var str = JSON.stringify(obj)
  if (str !== undefined) {
    return JSON.parse(str)
  } else {
    return null
  }
}

function rejectWith (message) {
  return Promise.reject(new Error(message))
}

function cancelTimeout (delay, message) {
  return new Promise(function (_, reject) {
    setTimeout(function () {
      return reject(new Error(message))
    }, delay)
    return /* () */ 0
  })
}

export {expectMatches, objToJson, rejectWith, cancelTimeout}
/* No side effect */
